# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_count_in_disc <- function(X, Y, x, y, radius, ncpu) {
    .Call('_lidRplugins_C_count_in_disc', PACKAGE = 'lidRplugins', X, Y, x, y, radius, ncpu)
}

C_li2012_auto <- function(las, dt1, dt2, Zu, th_tree, radius) {
    .Call('_lidRplugins_C_li2012_auto', PACKAGE = 'lidRplugins', las, dt1, dt2, Zu, th_tree, radius)
}

